name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup system repositories
        run: |
          sudo apt update
          sudo apt dist-upgrade
      - name: Install fonts
        run: |
          echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
          sudo apt install ttf-mscorefonts-installer
      - name: Setup XeLaTeX
        run: |
          sudo apt install texlive-xetex
      - name: Compilation
        run: xelatex -synctex=1 -interaction=nonstopmode -file-line-error docs.tex
